return {
  ["redpop"] = {
    kickedupdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      alwaysvisible      = true,
      properties = {
        airdrag            = 0.95,
        alwaysvisible      = true,
        colormap           = [[1 0 0 0.01   0.2 0 0 0.01   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 0.1, 0]],
        numparticles       = 30,
        particlelife       = 15,
        particlelifespread = 5,
        particlesize       = 40,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 1,
        pos                = [[0, 1, 0]],
        sizegrowth         = 2,
        sizemod            = 0.96,
        texture            = [[largelove]],
        useairlos          = true,
      },
    },
  },
  ["blackpop"] = {
    kickedupdirt = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      alwaysvisible      = true,
      properties = {
        airdrag            = 0.9,
        alwaysvisible      = true,
        colormap           = [[0 0.1 0 0.1   0 0 0 0.05   0 0 0 0.01]],
        directional        = true,
        emitrot            = 0,
        emitrotspread      = 180,
        emitvector         = [[0, 1, 0]],
        gravity            = [[0, 1, 0]],
        numparticles       = 30,
        particlelife       = 15,
        particlelifespread = 5,
        particlesize       = 90,
        particlesizespread = 1,
        particlespeed      = 20,
        particlespeedspread = 10,
        pos                = [[r100 -50, r100 -50, r100 -50]],
        sizegrowth         = 5,
        sizemod            = 0.98,
        texture            = [[flare]],
        useairlos          = true,
      },
    },
  },
}
