return {
  features = {},
  meta = {
    areas = {},
    info = {
      author = "gajop",
      description = "",
      name = "gajop's Scenario",
      version = "1",
    },
    teams = {
      [1] = {
        id = 1,
        team = {
          allyTeam = 1,
          gaia = false,
          id = 1,
          name = "1",
          side = "",
          allies = {
            [1] = 1,
          },
          color = {
            a = 1,
            b = 0,
            g = 0,
            r = 7.8431373e-01,
          },
        },
      },
      [2] = {
        id = 2,
        team = {
          ai = true,
          allyTeam = 2,
          gaia = true,
          id = 2,
          name = "2",
          side = "",
          allies = {
            [1] = 2,
          },
          color = {
            a = 1,
            b = 1,
            g = 1,
            r = 1,
          },
        },
      },
      [3] = {
        id = 0,
        team = {
          allyTeam = 0,
          gaia = false,
          id = 0,
          name = "0",
          side = "",
          allies = {
            [1] = 0,
          },
          color = {
            a = 1,
            b = 1,
            g = 3.5294118e-01,
            r = 3.5294118e-01,
          },
        },
      },
    },
    triggers = {},
    variables = {},
  },
  units = {
    [1] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 29,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 4780,
      y = 1389.1182,
      z = 6028,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [2] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 31,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 4916,
      y = 1401.0315,
      z = 5892,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [3] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 42,
      neutral = false,
      teamId = 1,
      tooltip = "MushroomSpawn - mushroomspawn",
      unitDefName = "mushroomspawn",
      x = 6844,
      y = 1537.0789,
      z = 7028,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [4] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 11,
      neutral = false,
      teamId = 1,
      tooltip = "Base - base",
      unitDefName = "base",
      x = 5028,
      y = 1407.8519,
      z = 5740,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [5] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 10,
      neutral = false,
      teamId = 1,
      tooltip = "Base - base",
      unitDefName = "base",
      x = 5060,
      y = 1397.1403,
      z = 5436,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [6] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 27,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion2 - expansion2",
      unitDefName = "expansion2",
      x = 4084,
      y = 1368.9651,
      z = 6268,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [7] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 16,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion1 - expansion1",
      unitDefName = "expansion1",
      x = 5116,
      y = 1382.4806,
      z = 5100,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [8] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 6,
      neutral = false,
      teamId = 1,
      tooltip = "Base - base",
      unitDefName = "base",
      x = 4396,
      y = 1369.7205,
      z = 5508,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [9] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 13,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion1 - expansion1",
      unitDefName = "expansion1",
      x = 4788,
      y = 1376.2894,
      z = 5148,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [10] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 33,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 5092,
      y = 1416.0347,
      z = 5796,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [11] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 30,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 4884,
      y = 1400.5966,
      z = 6116,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [12] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 40,
      neutral = false,
      teamId = 1,
      tooltip = "MushroomSpawn - mushroomspawn",
      unitDefName = "mushroomspawn",
      x = 1820,
      y = 1590.9576,
      z = 5108,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [13] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 20,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion1 - expansion1",
      unitDefName = "expansion1",
      x = 5308,
      y = 1421.402,
      z = 5476,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [14] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 21,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion2 - expansion2",
      unitDefName = "expansion2",
      x = 4140,
      y = 1371.6888,
      z = 5764,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [15] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 19,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion1 - expansion1",
      unitDefName = "expansion1",
      x = 5372,
      y = 1410.4042,
      z = 5220,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [16] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 36,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 5084,
      y = 1421.6537,
      z = 6196,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [17] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 28,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion2 - expansion2",
      unitDefName = "expansion2",
      x = 3948,
      y = 1394.1193,
      z = 6076,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [18] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 12,
      neutral = false,
      teamId = 1,
      tooltip = "Base - base",
      unitDefName = "base",
      x = 4788,
      y = 1388.1454,
      z = 5900,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [19] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 17,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion1 - expansion1",
      unitDefName = "expansion1",
      x = 5188,
      y = 1402.4963,
      z = 5316,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [20] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 23,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion2 - expansion2",
      unitDefName = "expansion2",
      x = 4116,
      y = 1368.9423,
      z = 6124,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [21] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 43,
      neutral = false,
      teamId = 1,
      tooltip = "MushroomSpawn - mushroomspawn",
      unitDefName = "mushroomspawn",
      x = 6796,
      y = 1569.3512,
      z = 5412,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [22] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 15,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion1 - expansion1",
      unitDefName = "expansion1",
      x = 4988,
      y = 1374.2981,
      z = 4948,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [23] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 18,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion1 - expansion1",
      unitDefName = "expansion1",
      x = 5236,
      y = 1392.746,
      z = 5108,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [24] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 44,
      neutral = false,
      teamId = 1,
      tooltip = "MushroomSpawn - mushroomspawn",
      unitDefName = "mushroomspawn",
      x = 5316,
      y = 1439.8041,
      z = 2508,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [25] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 8,
      neutral = false,
      teamId = 1,
      tooltip = "Base - base",
      unitDefName = "base",
      x = 4484,
      y = 1384.3002,
      z = 5308,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [26] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 24,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion2 - expansion2",
      unitDefName = "expansion2",
      x = 4372,
      y = 1371.9406,
      z = 5948,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [27] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 35,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 5196,
      y = 1430.4657,
      z = 6012,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [28] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 38,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 5324,
      y = 1442.7567,
      z = 5956,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [29] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 41,
      neutral = false,
      teamId = 1,
      tooltip = "MushroomSpawn - mushroomspawn",
      unitDefName = "mushroomspawn",
      x = 2884,
      y = 1434.5055,
      z = 7484,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [30] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 34,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 5180,
      y = 1424.469,
      z = 5820,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [31] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 39,
      neutral = false,
      teamId = 1,
      tooltip = "MushroomSpawn - mushroomspawn",
      unitDefName = "mushroomspawn",
      x = 4116,
      y = 1388.8779,
      z = 3012,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [32] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 37,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 5180,
      y = 1429.7221,
      z = 6140,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [33] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 14,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion1 - expansion1",
      unitDefName = "expansion1",
      x = 5044,
      y = 1381.9885,
      z = 5196,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [34] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 9,
      neutral = false,
      teamId = 1,
      tooltip = "Base - base",
      unitDefName = "base",
      x = 4860,
      y = 1372.2725,
      z = 5284,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [35] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 22,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion2 - expansion2",
      unitDefName = "expansion2",
      x = 3996,
      y = 1389.8966,
      z = 5844,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [36] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 7,
      neutral = false,
      teamId = 1,
      tooltip = "Base - base",
      unitDefName = "base",
      x = 4476,
      y = 1369.9493,
      z = 5756,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [37] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 32,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion3 - expansion3",
      unitDefName = "expansion3",
      x = 5036,
      y = 1414.1006,
      z = 6020,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [38] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 26,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion2 - expansion2",
      unitDefName = "expansion2",
      x = 4276,
      y = 1369.5374,
      z = 6116,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [39] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 25,
      neutral = false,
      teamId = 1,
      tooltip = "Expansion2 - expansion2",
      unitDefName = "expansion2",
      x = 4380,
      y = 1373.0619,
      z = 6236,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
    [40] = {
      angle = 0,
      experience = 0,
      fuel = 0,
      id = 5,
      neutral = false,
      teamId = 1,
      tooltip = "Spire - spire",
      unitDefName = "spire",
      x = 4688,
      y = 1370.6189,
      z = 5552,
      commands = {},
      losState = {
        los = true,
        radar = true,
        typed = true,
      },
      rules = {
        n = 0,
      },
      states = {
        active = false,
        cloak = false,
        firestate = 2,
        movestate = 0,
        ["repeat"] = false,
        trajectory = false,
      },
    },
  },
}
